; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 9600

;test_build_src = yes
test_filter = test_ultrason
;build_src_filter = +<us.cpp> -<main.cpp> -<IR.cpp>
monitor_filters = send_on_enter
monitor_echo = yes

lib_deps = 
    servo
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    https://github.com/jrullan/StateMachine.git
    mark170987/Button@^1.0.0
    https://github.com/Arduino-IRremote/Arduino-IRremote.git
    waspinator/AccelStepper @ ^1.64 
    nRF24/RF24 @ ^1.4.10
    stm32duino/STM32duino VL53L4CD
   
    
    
